services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - default

networks:
  default:
    driver: bridge
